'use client'

import { useEffect, useMemo, useState } from 'react'
import useSWR from 'swr'
import { create } from 'zustand'
import { Activity, AlertTriangle, ArrowUpRight, Check, ChevronDown, CircleDot, Clock3, Cloud, Code2, Copy, Crosshair, Database, ExternalLink, Filter, Globe2, LockKeyhole, Menu, MoreHorizontal, Network, Pause, Play, Radio, RefreshCw, Search, Server, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Wifi, X } from 'lucide-react'
import { cn } from '@/lib/utils'

type Verdict = 'PASS' | 'WARN' | 'BLOCK'
type EventItem = { id: string; time: string; verdict: Verdict; tier: string; scenario: string; region: string; latency: number; flags: string[] }
type Summary = { tiers: Record<string, { pass: number; warn: number; block: number }>; regions: { name: string; requests: number; pass: number; warn: number; block: number }[]; scenarios: { id: string; name: string; status: 'active' | 'paused'; events: number; rate: string }[] }

const scenarios = [
  { id: 'checkout-api', name: 'Checkout API', status: 'active' as const, events: 2184, rate: '18.2 req/s' },
  { id: 'account-login', name: 'Account Login', status: 'active' as const, events: 1458, rate: '12.1 req/s' },
  { id: 'search-index', name: 'Search Index', status: 'paused' as const, events: 804, rate: '6.7 req/s' },
  { id: 'webhook-ingress', name: 'Webhook Ingress', status: 'active' as const, events: 533, rate: '4.4 req/s' },
]

const initialSummary: Summary = {
  tiers: { edge: { pass: 92, warn: 6, block: 2 }, api: { pass: 78, warn: 16, block: 6 }, data: { pass: 88, warn: 9, block: 3 }, auth: { pass: 96, warn: 3, block: 1 } },
  regions: [{ name: 'us-east-1', requests: 1820, pass: 92, warn: 6, block: 2 }, { name: 'eu-west-1', requests: 1214, pass: 86, warn: 10, block: 4 }, { name: 'ap-southeast-1', requests: 904, pass: 81, warn: 14, block: 5 }, { name: 'sa-east-1', requests: 468, pass: 94, warn: 5, block: 1 }], scenarios,
}

const seedEvents: EventItem[] = [
  { id: 'evt_8f14', time: '12:42:18.092', verdict: 'PASS', tier: 'edge', scenario: 'Checkout API', region: 'us-east-1', latency: 42, flags: ['geo_ok', 'ip_reputation'] },
  { id: 'evt_8f13', time: '12:42:17.884', verdict: 'WARN', tier: 'api', scenario: 'Account Login', region: 'eu-west-1', latency: 118, flags: ['velocity_high', 'mfa_required'] },
  { id: 'evt_8f12', time: '12:42:17.701', verdict: 'PASS', tier: 'data', scenario: 'Search Index', region: 'us-east-1', latency: 27, flags: ['query_safe'] },
  { id: 'evt_8f11', time: '12:42:17.468', verdict: 'BLOCK', tier: 'auth', scenario: 'Webhook Ingress', region: 'ap-southeast-1', latency: 89, flags: ['token_invalid', 'replay_detected'] },
  { id: 'evt_8f10', time: '12:42:17.232', verdict: 'PASS', tier: 'edge', scenario: 'Checkout API', region: 'eu-west-1', latency: 55, flags: ['geo_ok'] },
]

const useEventStore = create<{ events: EventItem[]; add: (event: EventItem) => void; clear: () => void }>((set) => ({ events: seedEvents, add: (event) => set((state) => ({ events: [event, ...state.events].slice(0, 1000) })), clear: () => set({ events: [] }) }))
const fetcher = (url: string) => fetch(url).then((res) => res.ok ? res.json() : Promise.reject(new Error('Summary unavailable')))

function StatusDot({ tone }: { tone: 'green' | 'amber' | 'red' }) { return <span className={cn('inline-block size-2 rounded-full', tone === 'green' && 'bg-emerald-400', tone === 'amber' && 'bg-amber-400', tone === 'red' && 'bg-rose-400')} /> }
function Panel({ children, className }: { children: React.ReactNode; className?: string }) { return <section className={cn('rounded-lg border border-white/[0.08] bg-[#10141a] shadow-[0_16px_40px_rgba(0,0,0,0.16)]', className)}>{children}</section> }
function PanelTitle({ icon: Icon, title, action }: { icon: typeof Activity; title: string; action?: React.ReactNode }) { return <div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-3"><div className="flex items-center gap-2 text-xs font-semibold tracking-wide text-slate-200"><Icon className="size-4 text-cyan-400" />{title}</div>{action}</div> }

function Header({ connected, onReconnect }: { connected: boolean; onReconnect: () => void }) { return <header className="flex min-h-16 items-center justify-between border-b border-white/[0.08] px-4 md:px-7"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-md bg-cyan-400/10 text-cyan-300"><ShieldCheck className="size-5" /></div><div><div className="text-sm font-bold tracking-[0.14em] text-white">TRAFFIC ARMOUR</div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-500">harness / control plane</div></div></div><div className="hidden items-center gap-5 text-xs text-slate-400 md:flex"><span className="flex items-center gap-2"><StatusDot tone={connected ? 'green' : 'red'} />{connected ? 'Live stream connected' : 'Stream disconnected'}</span><span className="font-mono text-slate-500">v0.8.4</span><button onClick={onReconnect} className="flex items-center gap-2 rounded-md border border-white/10 px-3 py-1.5 text-slate-300 hover:bg-white/5"><RefreshCw className="size-3.5" />Reconnect</button></div><button aria-label="Open navigation" className="rounded-md p-2 text-slate-400 hover:bg-white/5 md:hidden"><Menu className="size-5" /></button></header> }

function Matrix({ summary, selectedTier, setSelectedTier }: { summary: Summary; selectedTier: string; setSelectedTier: (tier: string) => void }) { const tiers = Object.entries(summary.tiers); return <Panel><PanelTitle icon={Crosshair} title="VERDICT MATRIX" action={<span className="font-mono text-[10px] text-slate-500">LIVE / 1s WINDOW</span>} /><div className="overflow-x-auto p-4"><div className="grid min-w-[560px] grid-cols-[1.15fr_repeat(3,1fr)] gap-px overflow-hidden rounded-md border border-white/[0.08] bg-white/[0.07]"><div className="bg-[#151a22] p-3 font-mono text-[10px] uppercase text-slate-500">tier / verdict</div>{(['PASS','WARN','BLOCK'] as Verdict[]).map((v) => <div key={v} className="bg-[#151a22] p-3 text-center font-mono text-[10px] uppercase text-slate-500">{v}</div>)}{tiers.map(([tier, values]) => <div key={tier} className="contents"><button onClick={() => setSelectedTier(tier)} className={cn('bg-[#121821] p-3 text-left font-mono text-xs uppercase text-slate-300 hover:bg-cyan-400/10', selectedTier === tier && 'text-cyan-300')}>{tier}</button>{(['pass','warn','block'] as const).map((key) => <button key={key} onClick={() => setSelectedTier(tier)} className={cn('bg-[#121821] p-3 text-center font-mono text-sm font-semibold transition-colors hover:bg-white/[0.06]', key === 'pass' && 'text-emerald-300', key === 'warn' && 'text-amber-300', key === 'block' && 'text-rose-300', selectedTier === tier && 'bg-cyan-400/[0.08]')}>{values[key]}<span className="ml-1 text-[10px] font-normal text-slate-500">%</span></button>)}</div>)}</div></div></Panel> }

function GeoPanel({ regions }: { regions: Summary['regions'] }) { return <Panel><PanelTitle icon={Globe2} title="GEO BREAKDOWN" action={<button className="text-slate-500 hover:text-slate-200"><MoreHorizontal className="size-4" /></button>} /><div className="flex flex-col gap-3 p-4">{regions.map((region) => <div key={region.name} className="flex items-center gap-3"><div className="flex-1"><div className="mb-1 flex justify-between text-xs"><span className="font-mono text-slate-300">{region.name}</span><span className="font-mono text-slate-500">{region.requests.toLocaleString()} req</span></div><div className="flex h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><span style={{ width: `${region.pass}%` }} className="bg-emerald-400" /><span style={{ width: `${region.warn}%` }} className="bg-amber-400" /><span style={{ width: `${region.block}%` }} className="bg-rose-400" /></div></div><span className="w-9 text-right font-mono text-xs text-emerald-300">{region.pass}%</span></div>)}</div></Panel> }

function ScenarioPanel() { return <Panel><PanelTitle icon={Network} title="SCENARIOS" action={<button className="rounded border border-white/10 px-2 py-1 text-[10px] text-slate-400 hover:bg-white/5">+ New</button>} /><div className="flex flex-col">{scenarios.map((scenario) => <a href={`/scenarios/${scenario.id}`} key={scenario.id} className="group flex items-center gap-3 border-b border-white/[0.06] px-4 py-3 last:border-0 hover:bg-white/[0.025]"><StatusDot tone={scenario.status === 'active' ? 'green' : 'amber'} /><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-200">{scenario.name}</div><div className="font-mono text-[10px] text-slate-500">{scenario.events.toLocaleString()} events · {scenario.rate}</div></div><ArrowUpRight className="size-3.5 text-slate-600 transition group-hover:text-cyan-300" /></a>)}</div></Panel> }

function Feed({ events, filter, setFilter }: { events: EventItem[]; filter: string; setFilter: (filter: string) => void }) { const filtered = events.filter((e) => filter === 'ALL' || e.verdict === filter); return <Panel className="min-h-[460px]"><PanelTitle icon={Activity} title="ACTIVITY FEED" action={<div className="flex items-center gap-1">{['ALL','PASS','WARN','BLOCK'].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn('rounded px-2 py-1 font-mono text-[10px]', filter === item ? 'bg-white/10 text-white' : 'text-slate-500 hover:text-slate-300')}>{item}</button>)}</div>} /><div className="divide-y divide-white/[0.06]">{filtered.map((event) => <div key={event.id} className="group grid grid-cols-[76px_58px_1fr_auto] items-center gap-3 px-4 py-3 hover:bg-white/[0.025]"><span className="font-mono text-[10px] text-slate-600">{event.time}</span><span className={cn('w-fit rounded px-1.5 py-0.5 font-mono text-[10px] font-bold', event.verdict === 'PASS' && 'bg-emerald-400/10 text-emerald-300', event.verdict === 'WARN' && 'bg-amber-400/10 text-amber-300', event.verdict === 'BLOCK' && 'bg-rose-400/10 text-rose-300')}>{event.verdict}</span><div><div className="flex items-center gap-2 text-xs text-slate-300"><span className="font-mono text-slate-500">{event.tier}</span><span className="text-slate-600">/</span>{event.scenario}</div><div className="mt-1 flex gap-1.5">{event.flags.map((flag) => <span key={flag} className="font-mono text-[9px] text-slate-600">#{flag}</span>)}</div></div><span className="font-mono text-[10px] text-slate-500">{event.latency}ms</span></div>)}</div></Panel> }

function Telemetry() { const [open, setOpen] = useState(true); return <Panel><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between px-4 py-3 text-left"><span className="flex items-center gap-2 text-xs font-semibold tracking-wide text-slate-200"><Terminal className="size-4 text-cyan-400" />TELEMETRY</span><ChevronDown className={cn('size-4 text-slate-500 transition', !open && '-rotate-90')} /></button>{open && <div className="grid grid-cols-2 gap-4 border-t border-white/[0.07] p-4 md:grid-cols-4"><div><div className="font-mono text-[10px] uppercase text-slate-500">p50 latency</div><div className="mt-1 text-lg font-semibold text-slate-100">48<span className="ml-1 text-xs font-normal text-slate-500">ms</span></div></div><div><div className="font-mono text-[10px] uppercase text-slate-500">p95 latency</div><div className="mt-1 text-lg font-semibold text-amber-300">182<span className="ml-1 text-xs font-normal text-slate-500">ms</span></div></div><div><div className="font-mono text-[10px] uppercase text-slate-500">throughput</div><div className="mt-1 text-lg font-semibold text-cyan-300">41.4<span className="ml-1 text-xs font-normal text-slate-500">req/s</span></div></div><div><div className="font-mono text-[10px] uppercase text-slate-500">buffer</div><div className="mt-1 text-lg font-semibold text-slate-100">5<span className="ml-1 text-xs font-normal text-slate-500">/ 1k</span></div></div></div>}</Panel> }

export function TrafficDashboard() { const [connected, setConnected] = useState(true); const [selectedTier, setSelectedTier] = useState('edge'); const [filter, setFilter] = useState('ALL'); const { events, add } = useEventStore(); const { data } = useSWR<Summary>('/api/summary', fetcher, { fallbackData: initialSummary, refreshInterval: 1000, shouldRetryOnError: true }); useEffect(() => {
    const es = new EventSource('/api/events');
    es.onmessage = (e) => {
      try {
        const item = JSON.parse(e.data);
        if (item && item.id) add(item);
      } catch { /* ignore */ }
    };
    es.onerror = () => setConnected(false);
    es.onopen = () => setConnected(true);
    return () => es.close();
  }, [add]); const summary = data ?? initialSummary; return <main className="min-h-screen bg-[#090c10] text-slate-100"><Header connected={connected} onReconnect={() => setConnected(true)} /><div className="mx-auto flex max-w-[1600px] flex-col gap-5 p-4 md:p-7"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-cyan-400"><CircleDot className="size-3" /> live evaluation surface</div><h1 className="text-2xl font-semibold tracking-tight text-white md:text-3xl">Harness overview</h1><p className="mt-1 text-sm text-slate-500">Observe, inspect, and replay traffic decisions across your policy tiers.</p></div><div className="flex items-center gap-2"><button className="flex items-center gap-2 rounded-md border border-white/10 px-3 py-2 text-xs text-slate-300 hover:bg-white/5"><SlidersHorizontal className="size-3.5" />Filters</button><button className="flex items-center gap-2 rounded-md bg-cyan-400 px-3 py-2 text-xs font-semibold text-slate-950 hover:bg-cyan-300"><Play className="size-3.5" />Run scenario</button></div></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(320px,0.9fr)]"><div className="flex flex-col gap-5"><Matrix summary={summary} selectedTier={selectedTier} setSelectedTier={setSelectedTier} /><Feed events={events} filter={filter} setFilter={setFilter} /></div><div className="flex flex-col gap-5"><GeoPanel regions={summary.regions} /><ScenarioPanel /><Telemetry /></div></div><div className="flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-white/[0.07] pt-4 font-mono text-[10px] uppercase tracking-wide text-slate-600"><span className="flex items-center gap-2"><Wifi className="size-3" /> SSE /summary</span><span className="flex items-center gap-2"><Database className="size-3" /> FIFO 1,000 events</span><span className="flex items-center gap-2"><Clock3 className="size-3" /> refreshed just now</span><span className="ml-auto flex items-center gap-2 text-emerald-400"><StatusDot tone="green" /> all systems nominal</span></div></div></main> }

export default TrafficDashboard

function UnusedIcons() { return <div className="hidden"><AlertTriangle /><Cloud /><Code2 /><Copy /><Filter /><LockKeyhole /><Pause /><Radio /><Search /><Server /><Sparkles /><X /></div> }
